apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-gamedb
spec:
  selector:
    matchLabels:
      app: mysql-gamedb
  template:
    metadata:
      labels:
        app: mysql-gamedb
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_USER
          value: game_user
        - name: MYSQL_PASSWORD
          value: game_password
        - name: MYSQL_DATABASE
          value: gamedb
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-gamedb-pvc
      - name: initdb
        configMap:
          name: gamedb-initdb